FROM node:8-alpine
RUN mkdir /app
WORKDIR /app
COPY package.json /app
# RUN npm install -g yarn
# RUN npm install -g babel-cli
RUN npm install
COPY . /app
ENV NODE_ENV=production
ENV REACT_APP_GA=${REACT_APP_GA}
ENV REACT_APP_GRAPHQL=${REACT_APP_GRAPHQL}
ENV REACT_APP_SUBSCRIBERS=${REACT_APP_SUBSCRIBERS}
ENV REACT_APP_FB_APP_ID=${REACT_APP_FB_APP_ID}
ENV REACT_APP_GOOGLE_AD_CLIENT=${REACT_APP_GOOGLE_AD_CLIENT}
ENV REACT_APP_STRIPE_KEY=${REACT_APP_STRIPE_KEY}
RUN npm run build
EXPOSE 3000
CMD npm run start:server
